---
#base: https://id.svenskfilmdatabas.se/
base: http://localhost:8080/
cache: true
store: /data/rdfstore
sparql: true

title: FFSLOD Testbed (Sfdb)
description: 'This is a testbed for <a href="https://github.com/marma/ffslod">FFSLOD</a>, A dockerized tool to coax Linked data and SPARQL support out of an obstructing site through a combination of RDFa, URL and content negotiation, or as a last attempt: a separate site for identifiers and parsing HTML with regexp. This particular instance is configured to mirror <a href="http://www.svenskfilmdatabas.se/">Svensk filmdatabas</a> and is being populated lazily, i.e when resurces are asked for e.g by clicking on links.'
empty_message: '<b>Well, shit.</b> The database seem to be completely empty. Try <a href="/person/173874">this link</a> to add Mai Zetterling and explore from there.'

sparql_examples:
    - title: All movies
      query: "PREFIX schema:  <https://schema.org/>\n

SELECT ?uri ?name WHERE {\n
  ?uri a schema:Movie .\n
  ?uri schema:name ?name .\n
}\n
LIMIT 10"

    - title: All movies starring Cary Elwes
      query: "PREFIX schema:  <https://schema.org/>\n

SELECT ?movie ?title WHERE {\n
  ?actor schema:name \"Cary Elwes\" .\n
  ?movie schema:actor ?actor .\n
  ?movie schema:name ?title .\n
}
LIMIT 10"

    - title: directors that worked with actors that worked with Mai Zetterling
      query: "PREFIX schema:  <https://schema.org/>\n

SELECT distinct ?director ?name WHERE {\n
  ?mai a schema:Person .\n
  ?mai schema:name \"Mai Zetterling\" .\n
  ?movie schema:director ?mai .\n
  ?movie schema:actor ?actor .\n
  ?movie2 schema:actor ?actor .\n
  ?movie2 schema:director ?director .\n
  ?director schema:name ?name .\n
}\n
LIMIT 100"

urls:
  - match: "person/(?P<id>[0-9]+)"
    target: "http://www.svenskfilmdatabas.se/sv/item/?type=person&itemid={id}"
    mode: xslt

    config:
      type: https://schema.org/Person
      xslt: sfdb-person

  - match: "movie/(?P<id>[0-9]+)"
    target: "http://www.svenskfilmdatabas.se/sv/item/?type=film&itemid={id}"
    mode: xslt

    config:
      type: https://schema.org/Movie
      xslt: sfdb-movie

